### ISSUE TITLE
meteor files missing

### ISSUE THREAD

**Issue by blahah** [joeyklee/mozmap2015#10]
@joeyklee can you take a look at the meteor app directory? The `.meteor` directory needs to be committed and pushed.

**Comment by joeyklee** [comment]
Checking this out now!

**Comment by joeyklee** [comment]
So does this mean I should also push the "local" folder that was ignored in the .gitignore?

**Comment by blahah** [comment]
No, meteor has its own .gitignore which ignores things specific to your machine. But the `.meteor` should be added and committed.

**Comment by blahah** [comment]
expanding... the `local` directory is already ignored by meteor. If you just `git add .meteor && git commit -m 'meteor files' && git push`, it will automatically leave out the `local` dir in `.meteor`

**Comment by joeyklee** [comment]
right - so you mean this thing? https://github.com/joeyklee/mozmap2015/tree/master/mozmap

**Comment by blahah** [comment]
uhh.... yeah. _scratches head_

sorry, when `meteor` claimed it wasn't a meteor app, I assumed.

in that case, I've got a situation where...

```
~/c/m/mozmap master ❯ meteor add meteorhacks:npm                                                                                                                                                                                                                   [ruby-2.2.0]
add: You're not in a Meteor project directory.

To create a new Meteor project:
  meteor create <project name>
For example:
  meteor create myapp

For more help, see 'meteor --help'.
~/c/m/mozmap master ❯ pwd                                                                                                                                                                                                                                          [ruby-2.2.0]
/Users/rds45/code/mozmap2015/mozmap
~/c/m/mozmap master ❯
```

**Comment by joeyklee** [comment]
Issue solved by removing the "packages" and "packages.json" from the .gitignore.
