### ISSUE TITLE
layout

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/mozmap2015#3]
- x-axis = time
- y-axis = space
- add information box on session click

**Comment by blahah** [comment]
Going to tackle this next

**Comment by blahah** [comment]
Steps to get x axis working:
- function to add a datetime to each session, based on the `scheduleBlock` and `start` values
- create a D3 time scale covering the duration of mozfest
- modify the `makeLines` function of the `Transit.add` view

**Comment by blahah** [comment]
things to remember:
- [x] grab the [spaces data](http://mozilla.github.io/mozfest-schedule-app/spaces.json) and use it to get icons & descriptions for each space
- [x] add branching to lines (we have multiple concurrent sessions on a pathway many times)
- [x] padding at the edges of spaces
- [x] rewrite the path drawing algorithm
- [x] analyse pathway sharing between spaces, then order the spaces to minimise distances that have to be crossed by lines
