### ISSUE TITLE
have a single floating div containing info

### ISSUE THREAD

**Issue by blahah** [joeyklee/mozmap2015#7]
- [x] on start it shows info about the whole map
- [x] when hovering over a pathway it shows info about that pathway
- [x] when hovering over a station it shows info about that station

**Comment by blahah** [comment]
just to elaborate - I'm imagining we should have a `div` with `position: absolute` that floats in a corner. Initially it can just contain another `div`, and we set the content of the inner `div` to be information about whatever the user has selected. If the user hasn't selected anything, it reverts to showing info about the whole map. thoughts @joeyklee ?

**Comment by joeyklee** [comment]
+1 for this idea.

(alternatively we can also use a button to trigger a modal - but I think the original idea makes the info more accessible.)

**Comment by joeyklee** [comment]
Added info box and mouseover on station!
